version: '3.3'
services:
  psql:
    container_name: ets2-db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - ./data/psql:/var/lib/postgresql/data
    networks:
      - ets2
    env_file:
      - .env

  backend:
    container_name: ets2-backend
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfiles/backend.dockerfile
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./:/usr/backend
      - /usr/backend/node_modules
    networks:
      - ets2
    env_file:
      - .env
    depends_on:
      - psql

networks:
  ets2:
    driver: bridge
